### PR TITLE
Fix `grafana_user` and switch to using `flush`

### LINKED ISSUE #121: Cannot create users as Admin
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.2
- Ruby: 2.5.1
- Distribution:
- Module version: 4.4.1

## How to reproduce (e.g Puppet code you use)

```
$admin_map = {
    $admin_user => {
      theme            => 'light',
      grafana_url      => 'http://localhost:3000',
      grafana_user     => 'bob',
      grafana_password => 'bobobobobobob',
      is_admin         => true,
      password         => 'bob,
      email            => "bob@localhost"
    }
  }
create_resources('grafana_user', $admin_map)

```

## What are you seeing

A user who is not an admin even though it is specified in the type

## What behaviour did you expect instead

A user who is an admin

## Any additional information you'd like to impart

The code in `lib/puppet/provider/grafana_user/grafana.rb` creates a user if it doesn't exist and sets password and permissions if it does exist. In the create call it uses `isGrafanaAdmin` which I think is an unsupported parameter to a POST. It therefore beomces impossible to create an admin user.

OR I have made a huge misunderstanding

### PR DESCRIPTION
**Pull request by alexjfisher**
Previously `save_user` was being called once per changed property and
calls were also being made to update user properties, password and the
admin flag regardless of whether these properties needed updating.

Using `flush` is more efficient.

* `full_name` is fixed (it was previously a parameter instead of a property).
* When a user is created, `is_admin` is correctly set in a single Puppet run.
* Properties can be managed individually.
* Instead of making `password` mandatory, (when creating a user), if
  `password` isn't specified, a random one is used.

Fixes #121

### CODE REVIEW

File: lib/puppet/provider/grafana_user/grafana.rb [hunk 1]
```diff
@@ -48,79 +51,82 @@ def name
   end
 
   def name=(value)
-    resource[:name] = value
```
Comment (alexjfisher) [inline lib/puppet/provider/grafana_user/grafana.rb:51]: These lines didn't actually do anything.  `resource[:foo]` was already `value`. (The function wouldn't have been called if the property was not set)

File: lib/puppet/type/grafana_user.rb [hunk 2]
```diff
@@ -57,7 +57,6 @@ def insync?(_is)
   newproperty(:is_admin) do
     desc 'Whether the user is a grafana admin'
     newvalues(:true, :false)
-    defaultto :false
```
Comment (alexjfisher) [inline lib/puppet/type/grafana_user.rb:60]: Now that `update_admin_flag` is only called if the property has been set, there is no need for a default here (and defaults for _properties_ are generally a bad thing).

**Review by bastelfreak — APPROVED** [review]
