### PR TITLE
Fix dashboard api call in grafana_dashboard

### LINKED ISSUE #261: grafana_dashboards ov version 9.0.1 does not work with Grafana 6.7.6
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.23.0 (Puppet Enterprise 2019.8)
- Ruby: ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]
- Distribution: Red Hat Enterprise Linux Server release 7.9 (Maipo)
- Module version: 9.0.1

## How to reproduce (e.g Puppet code you use)
```
grafana_dashboard { $dashboard_name:
        grafana_url      => "https://${::fqdn}/grafana",
        grafana_api_path => '/grafana/api',
        grafana_user     => 'admin',
        grafana_password => $grafana_admin_password,
        folder           => $folder,
        content          => file("profiles_monitoring/grafana/dashboards/${dashboard}.json"),
        require          => Grafana_folder[$folders],
      }
```
## What are you seeing
```
Could not evaluate: Fail to retrieve dashboard disk (HTTP response: 404/{"message":"Dashboard not found"})
```
## What behaviour did you expect instead
The resource is skipped, as the dashboard already exists or the creation of the dashboard happens for the ones which do not exist yet.

## Any additional information you'd like to impart

The old module version 7.0.0 used the following URL in lib/puppet/provider/grafana_dashboard/grafana.rb function find_dashboard:
```
 response = send_request('GET', format('%s/dashboards/db/%s', resource[:grafana_api_path], slug))
```
whereas v 9.0.1 now uses
```
response = send_request('GET', format('%s/dashboards/uid/%s', resource[:grafana_api_path], slug))
```
The latter does not exist on grafana 6.7.5/6.7.6

### PR DESCRIPTION
**Pull request by joernott**
#### Pull Request (PR) description
The grafana_dashboard function was changed from using the old deprecated api to the recommended endpoint using the uid. However, the module still passed the dashboard title to the API instead of the uid, always resulting in a dashboard not found error. This PR fixes the problem.

#### This Pull Request (PR) fixes the following issues
Fixes #261

### CODE REVIEW

**Review by root-expert — APPROVED** [review]

**Comment by joernott** [comment]
I found another issue I fixed: When the code was changed, the uid was overwritten by slug (normalized string derived from the title). This breaks existing dashboards by changing their UID (and applications using them). 

There is also an idempotence issue, I am currently tracking down. The dashboards are being updated every puppet run. I use the JSON export provided by grafana as input but that seems to differ from what the module uses to assert changes. So, before merging this PR, I would like to figure out, what is causing the problem.

**Comment by joernott** [comment]
The idempotence issue was actually caused by me taking the json from the Export/Share dashboard functionality (or the API call to /dashboards/uid/<uid> without removing the fields "id", "uid", "title" and "version" from it. As the ruby code merges these fields into the hash, the order of fields changes due to the way ruby works. This results in the comparation between current and target to fail as the field order of the two hases is different. I added a sentence to the README for other users to stumble upon it.

File: lib/puppet/provider/grafana_dashboard/grafana.rb [hunk 1]
```diff
@@ -132,15 +133,15 @@ def save_dashboard(dashboard)
     data = {
       dashboard: dashboard.merge('title' => resource[:title],
                                  'id' => @dashboard ? @dashboard['id'] : nil,
-                                 'uid' => slug,
+                                 'uid' => @dashboard ? @dashboard['uid'] : nil,
```
Comment (root-expert) [inline lib/puppet/provider/grafana_dashboard/grafana.rb:136]: Is that nil for grafana to auto-generate it?

File: lib/puppet/provider/grafana_dashboard/grafana.rb [hunk 2]
```diff
@@ -160,10 +161,12 @@ def create
   end
 
   def destroy
-    response = send_request('DELETE', format('%s/dashboards/uid/%s', resource[:grafana_api_path], slug))
+    db = dashboards.find { |x| x['title'] == slug }
```
Comment (root-expert) [inline lib/puppet/provider/grafana_dashboard/grafana.rb:164]: Here we are destroying the dashboard based on the slug, but `find_dashboard` function uses `resource[:title]`.
Probably slug is more suitable, but we are creating dashboards with `resource[:title]` as title. This can cause problems in case `title` contains dashes and spaces.

**Review by root-expert — COMMENTED** [review]
Thanks for the PR! Have you tested if that works for both old generated dashboard and new generated?

The idea of using uid to create dashboard was to completely replace slug with uid. But yes I agree no migration was provided for old dashboards

**Comment by root-expert** [comment]
> The idempotence issue was actually caused by me taking the json from the Export/Share dashboard functionality (or the API call to /dashboards/uid/ without removing the fields "id", "uid", "title" and "version" from it. As the ruby code merges these fields into the hash, the order of fields changes due to the way ruby works. This results in the comparation between current and target to fail as the field order of the two hases is different. I added a sentence to the README for other users to stumble upon it.

About this. There have been multiple PRs, as far as I saw, in the past trying to address the idempotence issue. There are some measures in places to avoid this ([here](https://github.com/voxpupuli/puppet-grafana/blob/master/lib/puppet/provider/grafana_dashboard/grafana.rb#L150-L152) and [here](https://github.com/voxpupuli/puppet-grafana/blob/master/lib/puppet/type/grafana_dashboard.rb#L29-L31)). If you think you can help with that it would be awesome! As far as I see, as a first step in the second link we need to add `uid` parameter to the list.

From your comment, I suppose after merging the two hashes we can sort it as well to ensure the order doesn't change.

File: lib/puppet/provider/grafana_dashboard/grafana.rb (hunk 1 above)
Comment (joernott) [reply lib/puppet/provider/grafana_dashboard/grafana.rb:136]: yes, according to https://grafana.com/docs/grafana/latest/http_api/dashboard/

File: lib/puppet/provider/grafana_dashboard/grafana.rb (hunk 2 above)
Comment (joernott) [reply lib/puppet/provider/grafana_dashboard/grafana.rb]: Good idea, fixed that

File: lib/puppet/provider/grafana_dashboard/grafana.rb (hunk 1 above)
Comment (root-expert) [reply lib/puppet/provider/grafana_dashboard/grafana.rb:136]: Thanks for confirming

**Comment by joernott** [comment]
I am not that skilled in ruby to actually solve these idempotence issues in the code. I have encountered something similar (when handling yaml files) in [https://github.com/voxpupuli/puppet-elasticsearch/blob/master/lib/puppet_x/elastic/hash.rb](https://github.com/voxpupuli/puppet-elasticsearch/blob/master/lib/puppet_x/elastic/hash.rb), but that thing is scary...

**Comment by joernott** [comment]
Fixed the acceptance test of the folder and set the uid to slug for new dashboards. By setting it to slug, we become predictable and by not assuming its slug, we are backwards compatible

**Review by bastelfreak — APPROVED** [review]

File: spec/acceptance/grafana_folder_spec.rb [hunk 3]
```diff
@@ -139,7 +139,7 @@ class { 'grafana':
       end
 
       it 'folder contains dashboard' do
-        shell('curl --user admin:admin http://localhost:3000/api/dashboards/uid/example-dashboard') do |f|
+        shell('curl --user admin:admin http://localhost:3000/api/search?query=example-dashboard') do |f|
```
Comment (root-expert) [inline spec/acceptance/grafana_folder_spec.rb:142]: Why the search query instead of uid since the uid is now predictable?

Comment (joernott) [reply spec/acceptance/grafana_folder_spec.rb:142]: The uid is only predictable when creating new dashboards. Even though I changed the behaviour for new and the old test works for now, I still consider it a more stable solution to not rely on uid=slug. The search works with the name, no matter what is in the uid field.
